### ISSUE TITLE
Consider adding pixelserv to resolve requests for ads

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#113]
dnsmasq resolves requests for ads to 127.0.0.1 where the requests presumably fail now. We could stand up a Pixelserv webserver that responds with a 1x1 transparent gif instead. This may have better performance (not sure what happens while the client is waiting to timeout the request to localhost) and it might render the page better.

http://proxytunnel.sourceforge.net/pixelserv.php

Also here: https://github.com/kvic-z/pixelserv-tls#pixelserv-tls

**Comment by ndtob** [comment]
Ever since the DNSMasq resolver / ad blocking was fixed performance has been instantaneous. No slowdowns or delays rendering webpages and ad blocking is working. Ad block also now works within apps.

**Comment by defunctio** [comment]
I'm not a huge fan of this solution, the only edge cases where I can see this being useful are;

- Incoming packets on lo are dropped by firewall on the client host - causing the browser to wait and timeout (does anyone apply firewall rules to loopback devices?)
- The client is running a web service on 127.0.0.1:80 and they receive a 404

Otherwise I can't think of a reason to implement this.

**Comment by dguido** [comment]
Yeah agree. Unless there is a pain point that this solves, let's leave it out.
