### ISSUE TITLE
UFW support

### ISSUE THREAD

**Issue by aviadmini** [trailofbits/algo#1132]
**Is your feature request related to a problem? Please describe.**
Existing UFW rules are broken on reboot. Running `ufw enable` overwrites algo stuff and fixes it (though doesn't add algo rules)

**Describe the solution you'd like**
What I'd like is not having to resort to third-party solution and have algo itself support ufw. One option is something like Nginx does - shows up in `ufw app list` *plus* option in config to not overwrite iptables (docker has that for example)

**Describe alternatives you've considered**
Running `ufw enable` automatically after boot to overwrite changes made by algo

**Comment by davidemyers** [comment]
Algo does have an option to not overwrite existing rules (I've not tried it myself). See `--skip-tags iptables` in [Scripted Deployment](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md). You'd have to take care of loading the necessary rules yourself.

Algo's rules are too complicated to be implemented using only `ufw` commands or the `ufw app` feature. It might be possible for Algo to use `ufw-framework(8)` instead of `netfilter-persistent` to load its rules, which would allow `ufw` rules to coexist. However just enabling `ufw` adds several implicit rules that might not be desired by Algo.

**Comment by aviadmini** [comment]
I've seen in #688 that having 500 & 4500 open for tcp and udp is sufficient to run algo. Since you say that rules are not that simple I assume there's more to it just opening ports. 
So, is it a good idea to open those ports or should I dig deeper and set up some more complicated rules?
*Note that I have very little experience with all of this*

**Comment by davidemyers** [comment]
Opening those ports in an _external firewall_ is sufficient to allow access _through_ to an Algo server. The rules on the Algo server itself are considerably more complicated.

Log in to your Algo server and have a look at `/etc/iptables/rules.v4` and `/etc/iptables/rules.v6`.
