### ISSUE TITLE
Connect the whole network to algo vpn server

### ISSUE THREAD

**Issue by maykino** [trailofbits/algo#1158]
Hi, I would like to connect my whole network to the algo vpn server on demand. Is there any recommended hardware solution that can support algo vpn out of the box and it's config profiles? 

I'm trying to look into OpenWrt and Wireguard but the whole configuration seems to be extremely confusing.

**Comment by davidemyers** [comment]
Algo is designed to support connections from individual clients, each of which communicates using a single IP address assigned by the Algo server (dynamically in the case of IPsec, statically in the case of WireGuard).

With a router you generally want to forward a range of addresses that are assigned on the router side. Using a router this way requires changes to the Algo configuration.

I've worked out the changes necessary in order to connect from a pfSense router using IPsec and posted them [here](https://github.com/davidemyers/algo-pfsense). The Algo-side changes should work for any router using IPsec, but you'd need to work out how to configure the router yourself.

**Comment by maykino** [comment]
I appreciate that. On the side note would it be easier to connect amazon fire to algo vpn? I couldnt find anything solid on that.

**Comment by davidemyers** [comment]
I'm not familiar with the Fire (or Android, for that matter) but if can you get the [WireGuard](https://play.google.com/store/apps/details?id=com.wireguard.android) app installed then it might work. Algo will generate QR codes you can scan from the app to easily get connected to your server.
