### ISSUE TITLE
audit.d fails on ubuntu

### ISSUE THREAD

**Issue by mrphs** [trailofbits/algo#117]
While installing on a non-cloud server I got this error:
```
RUNNING HANDLER [logging : restart auditd] *************************************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "failed": true, "msg": "Job for auditd.service failed because the control process exited with error code. See \"systemctl status auditd.service\" and \"journalctl -xe\" for details.\n"}
```
I can now connect to the server but it's unclear to me what steps were suppose to be taken after this and failed. While writing this, I thought perhaps having an indicator of where in the process we are is useful.

**Comment by defunctio** [comment]
Just to confirm, this was on a vanilla ubuntu 16.04 installation?

**Comment by mrphs** [comment]
Correct. Xenial (16.04) with Linux LTS kernel (4.4.0-45-generic).

**Comment by gunph1ld** [comment]
just checked on a clean installation, it works well.
Can you investigate in your system why the job for auditd.service failed ?
`systemctl status auditd.service`, `journalctl`, etc...

**Comment by mrphs** [comment]
Here's `systemctl status auditd.service`:

```
● auditd.service - Security Auditing Service
   Loaded: loaded (/lib/systemd/system/auditd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-10-28 19:31:48 UTC; 4s ago
  Process: 17438 ExecStartPost=/sbin/auditctl -R /etc/audit/audit.rules (code=exited, status=0/SUCCESS)
  Process: 17437 ExecStart=/sbin/auditd -n (code=exited, status=6)
 Main PID: 17437 (code=exited, status=6)

Oct 28 19:31:48 hostname systemd[1]: Stopped Security Auditing Service.
Oct 28 19:31:48 hostname systemd[1]: Starting Security Auditing Service...
Oct 28 19:31:48 hostname auditctl[17438]: The audit system is in immutable mode, no rule changes allowed
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Oct 28 19:31:48 hostname systemd[1]: Failed to start Security Auditing Service.
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Unit entered failed state.
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Failed with result 'exit-code'.
```

and `journalctl -xe`:
```
Oct 28 19:31:48 hostname systemd[1]: Starting Security Auditing Service...
-- Subject: Unit auditd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit auditd.service has begun starting up.
Oct 28 19:31:48 hostname auditd[17437]: The audit daemon is exiting.
Oct 28 19:31:48 hostname auditctl[17438]: The audit system is in immutable mode, no rule changes allowed
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Oct 28 19:31:48 hostname systemd[1]: Failed to start Security Auditing Service.
-- Subject: Unit auditd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit auditd.service has failed.
-- 
-- The result is failed.
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Unit entered failed state.
Oct 28 19:31:48 hostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=auditd comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct 28 19:31:48 hostname systemd[1]: auditd.service: Failed with result 'exit-code'.
Oct 28 19:31:48 hostname kernel: audit_printk_skb: 30 callbacks suppressed
Oct 28 19:31:48 hostname kernel: audit: type=1130 audit(1477683108.658:9065): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=auditd comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? termin

```

**Comment by mrphs** [comment]
Damn it! it was because I had an `+` in my email address.

**Comment by secured4u** [comment]
Hi Guys,
Maybe you can help me or suggest any solution.
I cannot run an auditd service no matter what I'm doing.
I reinstalled it several times restarts, but no matter what I'm doing it doesn't work.

Here is the error log:

● auditd.service - Security Auditing Service
     Loaded: loaded (/lib/systemd/system/auditd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2020-11-26 19:27:00 UTC; 2min 48s ago
       Docs: man:auditd(8)
             https://github.com/linux-audit/audit-documentation

Nov 26 19:27:00 WhiteHat systemd[1]: Starting Security Auditing Service...
Nov 26 19:27:00 WhiteHat auditd[1780]: Started dispatcher: /sbin/audispd pid: 1782
Nov 26 19:27:00 WhiteHat auditd[1780]: Error setting audit daemon pid (File exists)
Nov 26 19:27:00 WhiteHat auditd[1780]: Unable to set audit pid, exiting
Nov 26 19:27:00 WhiteHat auditd[1780]: The audit daemon is exiting.
Nov 26 19:27:00 WhiteHat systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
Nov 26 19:27:00 WhiteHat auditd[1780]: Error setting audit daemon pid (Permission denied)
Nov 26 19:27:00 WhiteHat audispd[1782]: No plugins found, exiting
Nov 26 19:27:00 WhiteHat systemd[1]: auditd.service: Failed with result 'exit-code'.
Nov 26 19:27:00 WhiteHat systemd[1]: Failed to start Security Auditing Service.

**Comment by nnaben** [comment]
I am having a similar problem too.
 auditd.service - Security Auditing Service
   Loaded: loaded (/lib/systemd/system/auditd.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Tue 2021-06-29 23:33:05 EDT; 27min a
     Docs: man:auditd(8)
           https://github.com/linux-audit/audit-documentation
  Process: 14956 ExecStart=/sbin/auditd (code=exited, status=6)

Jun 29 23:33:05 UbuntuDesktop systemd[1]: Starting Security Auditing Service...
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: Missing equal sign for line 38 in /
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: Not processing any more lines in /e
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: The audit daemon is exiting.
Jun 29 23:33:05 UbuntuDesktop systemd[1]: auditd.service: Control process exited
Jun 29 23:33:05 UbuntuDesktop systemd[1]: auditd.service: Failed with result 'ex
Jun 29 23:33:05 UbuntuDesktop systemd[1]: Failed to start Security Auditing Serv
...skipping...
● auditd.service - Security Auditing Service
   Loaded: loaded (/lib/systemd/system/auditd.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Tue 2021-06-29 23:33:05 EDT; 27min a
     Docs: man:auditd(8)
           https://github.com/linux-audit/audit-documentation
  Process: 14956 ExecStart=/sbin/auditd (code=exited, status=6)

Jun 29 23:33:05 UbuntuDesktop systemd[1]: Starting Security Auditing Service...
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: Missing equal sign for line 38 in /
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: Not processing any more lines in /e
Jun 29 23:33:05 UbuntuDesktop auditd[14956]: The audit daemon is exiting.
Jun 29 23:33:05 UbuntuDesktop systemd[1]: auditd.service: Control process exited
Jun 29 23:33:05 UbuntuDesktop systemd[1]: auditd.service: Failed with result 'ex
Jun 29 23:33:05 UbuntuDesktop systemd[1]: Failed to start Security Auditing Serv
I need a solution

**Comment by nnaben** [comment]
##krb5_key_file = /etc/audit/audit.key
distribute_network = no
-w /etc/passwd -p wa -k passwd  ..........................line 38
-w /etc/shadow -p wa -k shadow

**Comment by nnaben** [comment]
Guys I got my problem solved. I uninstalled using the purge command and reinstalled audited. it si now active likewise journalctl

sudo apt-get purge auditd 
sudo apt-get install auditd
