### ISSUE TITLE
Is Algo encripted my data really?

### ISSUE THREAD

**Issue by Sysetup** [trailofbits/algo#1201]
I have installed Algo in AWS Lightsail, it works apparently fine from a macOs. but when I execute a test typing in the terminal in my local machine (the client): 

`sudo tcpdump -i en0 ether host xx:xx:xx:xx:xx:xx` 

Between several lines I get this one:

`11:44:47.568951 IP 192.168.2.102.hosts2-ns > dynamic-ip-1915303312.cable.net.co.8805: Flags [R.], seq 0, ack 2448715559, win 0, length 0`

And this one is really my ISP. Is Algo encrypted fine my data?

Using Cocoa Packet Analyzer I get this too:

![screen shot 2018-11-13 at 11 58 02](https://user-images.githubusercontent.com/9453397/48429737-b4f76900-e73b-11e8-964b-5fea86ff87bf.png)

From my point of view, my data is not being encrypted. Am I right?

**Comment by davidemyers** [comment]
macOS will not send traffic destined for your local LAN out over IPsec.

**Comment by Sysetup** [comment]
> macOS will not send traffic destined for your local LAN out over IPsec.

That means that Algo using macOS as a client doesn't encrypt the data? with Linux, iOS, and Android it does?

**Comment by davidemyers** [comment]
Algo is used to create a personal VPN server in the cloud. A client device creates an encrypted tunnel between itself and the VPN server out on a remote network, and then sends all Internet-bound traffic over the tunnel. Once the traffic reaches the far side of the tunnel it is decrypted and routed to its destination as if it had originated from the VPN server.

For a majority of users it makes no sense to send traffic intended for a client on the local LAN out to the Internet through an encrypted tunnel. This would break many LAN-based services since so many of them depend on local broadcasts.

Therefore macOS and iOS IPsec clients do not send local LAN traffic out over the VPN tunnel to the Internet. Whether or not a Linux IPsec client does depends on how you configure it. WireGuard clients such as Android will also not interfere with local LAN traffic.

**Comment by Sysetup** [comment]
I want to understand a little bit of piece about you are writing here brother. You are telling that macOS clients don't send **local LAN traffic** over the VPN tunnel to the Internet. This means the tests I'm doing are not sending the packages the same way as when they are sent normally navigating with a web browser for example?

**Comment by davidemyers** [comment]
The tests you've shown above appear to be sniffing traffic on your local network, so you should see local traffic as well as traffic destined for the Internet. Only traffic destined for the Internet will be encrypted and tunneled to your Algo server.

When I run `sudo tcpdump -i en0` I see local traffic as well outbound packets of type `UDP-encap: ESP`. Those are IPsec encrypted packets destined for my Algo server.

**Comment by Sysetup** [comment]
> When I run `sudo tcpdump -i en0` I see local traffic as well outbound packets of type `UDP-encap: ESP`. Those are IPsec encrypted packets destined for my Algo server.

How can I be completely sure the outbound packets send to the internet are encrypted? What consistent technics exists?

**Comment by dguido** [comment]
Please get this type of user support from the gitter, this is not a bug in Algo.

**Comment by Sysetup** [comment]
> Please get this type of user support from the gitter, this is not a bug in Algo.

I agree with you, Alright!
