### ISSUE TITLE
Internet isn't working after connecting to the VPN server

### ISSUE THREAD

**Issue by lzzy12** [trailofbits/algo#1212]
I setup this on Ubuntu 18.04 VM on Google Cloud. But when I connect it from my android device through Wireguard, internet stops working.
Any help would be greatly appreciated. Please do mention any information you want me to provide.

**Comment by TC1977** [comment]
It's really hard to troubleshoot something like this without more specifics.

- Please include the text from the original install log, which starts `Please include the following block of text when reporting issues:`

- When you connect with Wireguard, is the connection definitely up?
- Are you able to ping your Algo server from your Android phone? Are you able to ping the outside world, e.g., google.com (and 8.8.8.8)?
- Can you connect with Wireguard on other clients, such as your Linux desktop or Mac?
- Can you connect to the Algo server and load web pages using a Mac or Windows machine, not using Wireguard?
- Can you SSH into the server and run the following diagnostics, and paste output (redacting your server IP):
```
wg-quick
sudo ipsec statusall
service dnscrypt-proxy status
service dnsmasq status #try this one if you enabled ad-blocking
```

**Comment by TC1977** [comment]
> Have same problem with local installation(Ubuntu 18.04 ).
> 

The original poster had a problem where Android clients connecting thru Wireguard caused "internet stops working" (whatever this means). You're saying that the Wireguard connection is up for both Linux and Android? Are you sure you have the same problem?

**Comment by SystemOfLife** [comment]
I believe,  topic starter meant that he can't connect to outside world (e.g. google.com) after establishing connection with his Algo server. In my situation, I can connect to server(ssh, and wg for example) , but after this I can't connect to any site.

**Comment by lzzy12** [comment]
Yes I too had an Ubuntu 18.04 local installation. And my problem is exactly as @SystemOfLife described

**Comment by davidemyers** [comment]
I assume both of you installed on a fresh instance of Ubuntu 18.04? Specifically, you didn't install any packages unrelated to Algo first, such as a firewall like UFW?

@SystemOfLife There's something odd about your posted output. You server has working IPv6, but your WireGuard status doesn't show an IPv6 address for the peer. That may be an error on Algo's part, but I don't know if that's causing your problems. Where is your server located?

@lzzy12 Since you're on GCE you don't have IPv6. Did you adjust the VPC Firewall Rules to allow Algo traffic in to your instance? You also might need to use the `max_mss:` option in `config.cfg` and deploy to a fresh instance due to the smaller MTUs on GCE.

**Comment by davidemyers** [comment]
@SystemOfLife Could you have exceeded your VPS bandwidth limit?
