### ISSUE TITLE
Suggestion. Digital Ocean Documentation - FW Setup

### ISSUE THREAD

**Issue by mikeruss** [trailofbits/algo#1215]
Digital Ocean offer a free firewall and I thought having the config would be useful to have in your setup doc.

These are the only rules I have setup and all works. If I need to SSH I will temporarity enable when in use.

Inbound Rules
Custom | TCP | 500 | All IPv4 All IPv6
Custom | TCP | 4500 | All IPv4 All IPv6
Custom | UDP | 500 | All IPv4 All IPv6
Custom | UDP | 4500 | All IPv4 All IPv6

Outbound Rules
ICMP | ICMP |   | All IPv4 All IPv6
All TCP | TCP | All ports | All IPv4 All IPv6
All UDP | UDP | All ports | All IPv4 All IPv6

**Comment by davidemyers** [comment]
Your rules break WireGuard. Also, you don't need 500/TCP or 4500/TCP. You don't actually need IPv6 access to any service but SSH since Algo clients only connect to servers over IPv4.

Here are my DigitalOcean rules, with SSH restricted to certain source addresses.

![](https://photos.smugmug.com/photos/i-KMkmb49/0/0362b296/X2/i-KMkmb49-X2.jpg)

Questions about the DigitalOcean firewall do come up from time to time, so perhaps it is worth documenting. Maybe I'll submit a PR.

**Comment by mikeruss** [comment]
Hey David - Thanks for sharing and I have updated.

**Comment by davidemyers** [comment]
@jwebbstevens The rules I posted are for Inbound. The defaults can be used for Outbound.

**Comment by jwebbstevens** [comment]
Amazing. Thanks.

**Comment by jackivanov** [comment]
It's already documented in [FAQ](https://github.com/trailofbits/algo/blob/master/docs/faq.md#what-inbound-ports-are-used)
