### ISSUE TITLE
Remove WireGuard KeepAlive and include as an option in config

### ISSUE THREAD

**Issue by digeratus** [trailofbits/algo#1251]
The default AlgoVPN installation creates wireguard conf files with the Persistent keepalive setting to 25. A setting of 25 makes sense behind some corporate firewalls and NAT, but not for mobile devices like Android or iOS.

Considering that the Wireguard conf available via Algo is meant to be for Android users, it should definitely be changed to 0. Othewise, users data usage will skyrocket.

**Comment by digeratus** [comment]
> Please at least make it configurable in config.cfg.
> 
> It isn’t clear to me that “25 makes sense behind some corporate firewalls and NAT, but not for mobile devices like Android or iOS.” Do very few people use Android / iOS with Algo behind NAT?

Hard to tell. But there's one thing I do know, an app that kills data is an app that won't be used for long. As it is on Android and iOS one can change that setting manually after installation. I believe the current setting is way too high.

https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence

**Comment by davidemyers** [comment]
My understanding is that `PersistentKeepalive` should not be needed when a WireGuard client is behind a firewall and/or NAT unless that client is providing some sort of network service and will need to listen for connections initiated systems on the other side of the firewall and/or NAT.

As far as data usage goes, I tried to run a test to see how much additional data `PersistentKeepalive` uses. While my testing methodology turned out to be flawed, it appeared that the data usage was much smaller than I expected. Has anyone else tried to measure how much data `PersistentKeepalive` generates?

**Comment by davidemyers** [comment]
I reran some tests and hopefully got it right this time. From what I can tell `PersistentKeepalive = 25` would use about 8 MB per *month*. 

So although unnecessary for most it doesn't appear to be detrimental in terms of data consumption. 

For mobile devices there may be an impact on battery life but I don't know how to measure that. For my iOS devices I'll continue to remove `PersistentKeepalive` since they work fine without it.

If anyone else gets different results please post them.

**Comment by adamluk** [comment]
This seems to have come about from issue #1068. I disable it though as no need for my usage. For mobile devices it doesn't make sense to enable - perhaps this should default to 0, with option in config?

**Comment by zx2c4** [comment]
Algo has little reason to enable PersistentKeepalive.
