### ISSUE TITLE
Incorrect private key usage when not using ssh-agent

### ISSUE THREAD

**Issue by dbrwn** [trailofbits/algo#126]
Working off ec2updates branch commit 475365007dacde59d54faa112c619ed63b8a812b on macOS Sierra.

Instance launches properly and `Wait for SSH to become available` task completes successfully.  The Install prerequisites task fails:

```
TASK [Install prerequisites] ***************************************************
fatal: [35.163.127.66]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '35.163.127.66' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
```

I was using an alternate keypair (ie., not id_rsa.pub).  I confirmed the instance launched and I could connected to it with my selected keypair.

I found that if I use the default filename for the public key file, it proceeds past the prerequisite install task, queries for passphrase, etc.

**Comment by defunctio** [comment]
This is due to the expected usage of ssh-agent where this may not always be the case. When changing from an alternate other than the default key and not using ssh-agent, the improper private key is used. 

517820e1d6aa755dffb74aaa37e236f5e8737804 this commit assigns the private key with the assumption that the private key is in the same location as the public key minus the .pub extension. It should resolve the immediate issue.

This may have undesired effect when using ssh-agent, I haven't tested. This could probably be made conditional by checking for the existence of the SSH_AUTH_SOCK env var or something similar if it is a problem.

**Comment by dbrwn** [comment]
@defunctio This commit resolves the issue I was having.  You are correct, I did not have the alternate id added into ssh-agent (which did happen to be running).   

Properly using ssh-agent (ie., I wasn't) is still probably the right way to resolve for the general case.
