### ISSUE TITLE
Misleading/manipulative readme

### ISSUE THREAD

**Issue by norlin** [trailofbits/algo#1274]
**Describe the bug**

In the Readme, there is a line:

> Does not install Tor, OpenVPN, or other risky servers

Meanwhile, in the FAQ, there is another line:

> Use Algo at your own risk

**To Reproduce**

Read the Readme and FAQ

**Expected behavior**

No manipulative, misleading or conflicting statements

**Comment by TC1977** [comment]
I will assume that this is not a troll attempt.

[Oxford dictionary definition of risk](https://en.oxforddictionaries.com/definition/us/risk) reproduced partially below:

```1A situation involving exposure to danger.
‘flouting the law was too much of a risk’
‘all outdoor activities carry an element of risk’

1.1in singular The possibility that something unpleasant or unwelcome will happen.
‘reduce the risk of heart disease’
as modifier ‘a high consumption of caffeine was suggested as a risk factor for loss of bone mass’

1.2with modifier A person or thing regarded as a threat or likely source of danger.
‘she's a security risk’
‘gloss paint can burn strongly and pose a fire risk’

1.3usually risks A possibility of harm or damage against which something is insured.

1.4with adjective A person or thing regarded as likely to turn out well or badly, as specified, in a particular context or respect.
‘Western banks regarded Romania as a good risk’

1.5 The possibility of financial loss.
as modifier ‘project finance is essentially an exercise in risk management’
```
Referring to definition 1.3, "Use at your own risk" is a common phrase in English meaning that Algo (or Trail of Bits) is not financially insuring you against the possibility that your VPN will somehow be compromised (most likely through user error).

"Risky" modifies "risk" as per definition 1.1, and is defined separately as "Full of the possibility of danger, failure, or loss." Algo uses IPsec and Wireguard, which are well regarded as minimizing the possibility of danger, failure, or loss.

**Comment by norlin** [comment]
@TC1977 thank you for the explanation, English is not my native language.

So, you're telling that Algo software and script are not "risky" at all and the "risk" word is just a legal "denial of responsibility" just in case?

Mostly, the question is not about the basic tech of the Algo project (IPSec and so on), rather about a lot of custom scripts which are not widely used and didn't get any third-party audition.

Is there any kind of proof why you're calling one of the most popular VPN software "risky" while implying that Algo's scripts are not risky?

Sorry for the lot of words, just I believe being completely clear in all the PR is one of the most important things for a security-related software.

**Comment by TC1977** [comment]
If your concern is over the Algo code rather than IPsec or strongSwan, then I suggest you spend some time reading the code for yourself. The custom scripts are open-source, not very large, and easily checked. I have no experience with Ansible, or Linux, and even I find it fairly easy to follow.

As far as why OpenVPN and Tor are considered "risky", I have no relationship with either Algo or TrailofBits and won't presume to speak for them. I'll refer you to the [release announcement](https://blog.trailofbits.com/2016/12/12/meet-algo-the-vpn-that-works/) which is linked in the very first paragraph of the readme. A google search for "OpenVPN compromise" also gives [an example from 2017](https://thehackernews.com/2017/06/openvpn-security-flaw_21.html).

I'll pretend for a few more seconds that this is not a trolling attempt, and in good faith refer you to [the Oxford definition of manipulative](https://en.oxforddictionaries.com/definition/manipulative) and [misleading](https://en.oxforddictionaries.com/definition/misleading). Read that and please understand that opening an issue with a title accusing people of being unscrupulous or lying isn't the best use of anyone's time.

No further responses from me.

**Comment by norlin** [comment]
That's sad that you're not going to be a clear and open project and prefer to mislead people. It's kinda a blocker for a security-focused project.
