### ISSUE TITLE
Lightsail

### ISSUE THREAD

**Issue by nsm11** [trailofbits/algo#14187]
The algovpn instance in Lightsail is deployed on a different server that then installation server, and it is not possible to ssh into the console. SSH stays in black screen.

**Comment by davidemyers** [comment]
When you use Algo to deploy to a supported cloud provider the SSH port will be changed to 4160 in order to reduce attempts to break in to the instance. This will break Lightsail's browser-based SSH feature which assumes SSH is on port 22.

When a cloud deployment finishes Algo prints to the screen the command line to use to log in to the server using SSH on the modified port.

You can also change `ssh_port` in `config.cfg` back to 22 before you deploy.

**Comment by nsm11** [comment]
ok thanks
