### ISSUE TITLE
clients sometimes need to ping outside world in order to be pinged by other clients

### ISSUE THREAD

**Issue by Jconn** [trailofbits/algo#14229]
occasionally, some of the clients on our vpn stop responding to pings from other clients on the vpn. 
These issues occur on Ubuntu 18.04 and 20.04 clients

If we ssh into the offending client through another network interface and ping any internet address or vpn client address, then the offending client starts responding to pings again. 

we've set the param `BetweenClients_DROP: false` which is what allows communication to work normally.

**Comment by davidemyers** [comment]
If there's a firewall between your AlgoVPN server and the "offending" client then the problem might be that the firewall states are expiring when the client is idle for a while. Try adding:
```
PersistentKeepalive = 25
```
to the client's WireGuard configuration so that it sends regular traffic and keeps the firewall states current.

**Comment by Jconn** [comment]
I will try that and wait a few weeks to see if the issue is gone

**Comment by davidemyers** [comment]
If `PersistentKeepalive` solves your problem you can have Algo add it to your WireGuard configs the next time you deploy a server by setting `wireguard_PersistentKeepalive` in [`config.cfg`](https://github.com/trailofbits/algo/blob/e5235e1bdc63a144d9bfea788264bbcecf0b9dcf/config.cfg#L125).
