### ISSUE TITLE
Query - How many user at a sametime this VPN can support?

### ISSUE THREAD

**Issue by Heenathacker** [trailofbits/algo#1423]
This is not a problem or feature request, How many concurrent users this VPN can support?

**Comment by davidemyers** [comment]
You can define slightly over 250 users in `config.cfg`. By default Algo will generate both a WireGuard and an IPsec configuration for each user, so that's about 500 concurrent connections *in theory*. You would need to use an appropriately sized instance from your cloud provider.

But I don't think managing that many users with Algo is practical. Modifying the list of users and running `./algo update-users` is likely to be very slow. You'll have to distribute the correct configuration files to each of your users yourself. If for some reason you need to deploy to a new server you'll have to distribute all of the configuration files all over again.

**Comment by Heenathacker** [comment]
what if I purchase a license or anything? will that be able to support 50,000 users? at a time 20,000 users?

**Comment by davidemyers** [comment]
Algo is free but [donations are accepted](https://github.com/trailofbits/algo#support-algo-vpn). The current limit is hardcoded. I don't think Algo is the best solution for you.

**Comment by jackivanov** [comment]
[Algo-ng](https://github.com/trailofbits/algo-ng) can handle thousands of users very fast (including update-users). It's under AGPLv3, and currently active development, not all features are ported yet

**Comment by Heenathacker** [comment]
Thank you so much for your help and reply.

**Comment by ramseth001** [comment]
@davidemyers can you give a ballpark estimate on how many connections a t2 micro (free tier/default) instance can support simultaneously?

**Comment by davidemyers** [comment]
@ramseth001 I don't know, I've never done any Algo capacity testing.
