### ISSUE TITLE
Unable to retrieve Ipv6CidrBlocks attribute for AWS::EC2::VPC / IAM permissions not sufficient for EC2 in eu-central-1

### ISSUE THREAD

**Issue by andreas-venturini** [trailofbits/algo#14383]
Hello,

I have created multiple Algo stacks in the past in `eu-central-1` using the minimum required IAM permissions as per https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md#minimum-required-iam-permissions-for-deployment)

Today I received the following error (obtained from the CloudFormation stack resources section)

> Unable to retrieve Ipv6CidrBlocks attribute for AWS::EC2::VPC, with error message You are not authorized to perform this operation. (Service: Ec2, Status Code: 403, Request ID: XXX, Extended Request ID: null)

I could reproduce this reliably in eu-central-1 (did not test any other region). I pulled latest master & only changed the following 2 values in the config (none of which should make a difference here):
* `ipsec_enabled: false`
* `size: t3a.nano`

I'm fairly certain that this is related to an issue w/ the minimum required IAM permissions outlined above as everything worked after I attached the AWS managed `AdministratorAccess` policy to my IAM user.

**Comment by glennschler** [comment]
@andreas-venturini  I have reproduced the issue in eu-central-1. The issue does not occur in my us-east-1. I am investigating.

**Comment by glennschler** [comment]
@andreas-venturini I had been able to see the error consistently over the past days as I searched for the IAM Policy actions related to this problem. Normally CloudTrail logging of API events show the actions needed in the IAM policy. In this case CloudTrail is not logging the actions related to this issue. 

I have identified two IAM policy actions needed. Though now I am not able to recreate the problem using the original IAM policy, in eu-central-1 or any region which I attempt. Until I recreate the issue again I cannot make a change to the document. If you are experiencing the issue, can you test with these actions added to your existing policy?

```
"ec2:DescribeNetworkAcls",
"ec2:DescribeVpcAttribute"
```

**Comment by glennschler** [comment]
I have reproduced the issue in eu-central-1 and several other regions, though not all regions fail. For the regions experiencing the issue, adding the following IAM profile action resolves the issue.

`ec2:DescribeNetworkAcls`

I will continue to investigate why there is a difference between regions before modifying the documentation.

**Comment by glennschler** [comment]
I suspect this was an issue with AWS which they resolved. It was witnessed every attempt during the first 3 weeks of the January in any region which only supports VPC. Regions in my account with classic EC2 supporting platforms did not experience the issue.  EC2 classic platforms are any region you launched before 2013-Dec-05. The issue was seen using Algo, as well as smaller mockups of the cloud formation stack launched using the AWS cli. Tested with IAM profiles assigned to an IAM user, as well as IAM assumed roles.

One indicator of a recent internal AWS change relevant to this issue, is that in the past AWS CloudTrail never logged the IAM action `ec2:ModifySubnetAttribute` regardless of Algo success or failure in any region. Now that event is always logged. This is the event which relates to Algo's cloudformation stack resource named "SubnetIPv6" which sets the VPC Subnet Ipv6CidrBlock attribute. The OP error message shows failure to retrieve this subnet attribute.

No Algo change is required to close this issue. Though the [minimum-required-iam-permissions-for-deployment.md](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md#minimum-required-iam-permissions-for-deployment) does have one ec2 event written with a wildcard. This should be changed to be more explicit showing the exact ec2 actions needed. I will submit a PR of the following change in reference to this issue, though not as a PR which fixes this issue:

```
"ec2:Associate*",
```

Should be changed to this explicit list of needed permissions
```
"ec2:AssociateVpcCidrBlock",
"ec2:AssociateSubnetCidrBlock",
"ec2:AssociateRouteTable",
"ec2:AssociateAddress",
```

**Comment by andreas-venturini** [comment]
@glennschler thanks for investigating so thoroughly. Your reasoning sounds plausible 👍
