### ISSUE TITLE
Inaccurate or misleading claims regarding OpenVPN & TLS in README

### ISSUE THREAD

**Issue by dantheman213** [trailofbits/algo#1439]
I have seen other tickets relating to this issue as well but I have not seen the core issues fully addressed. In your README you have this line:

> Does not install Tor, OpenVPN, or other risky servers
> Does not depend on the security of TLS

OpenVPN and IPSec can be both very secure or very insecure, depending on your configuration. In fact, a quick search on Google found this highly upvoted Reddit comment. Instead of re-inventing the wheel, I'll just provide an existing comprehensive list that you can refute in your README.

> It's the difference between:

> 1. user-space (ovpn) vs. kernel-space (IPsec).
> 2. opening 1 udp port (ovpn) on the firewall vs. 2-4 ports (isakmp, esp, ah, nat-t) (IPsec).
> 3. TLS on steroids (ovpn) vs. IKE (IPsec) for control.
> 4. DIY (ovpn) vs. vendor & IT support (IPsec).
> 5. Easy portability (ovpn) vs. difficult portability because of #1 (IPsec).
> 6. Ease of compatability with an external peer (ovpn) vs. various vendor implementations of IPsec.
> 7. Both can be tough to implement correctly.
> 8. Both have quite the learning curve.
> 9. Not so much documentation (ovpn) vs. very extensive documentation (IPsec).
> 10. Multicast support (ovpn) vs. GRE trickery (IPsec).
> 11. L2 support (ovpn) vs. L2TP trickery (IPsec).
> 12. Both are as secure (or insecure) as you make them, as they both support more or less the same ciphers & hashes. However, for IPsec, the supported features are limited by the vendor, which means it is slower to adopt emerging encryption tech (ECC, Quantum Encryption, newer stream ciphers) than OpenVPN.
> > 

> In short, if you're looking for top security, go with OpenVPN. The only reason to use IPsec nowadays is if you have no choice, or you're implementing an advanced commercial solution (SD-WAN).

Can you answer these questions in your README if you're going to provide such a strong opinion of what you consider best practices to security-focused professionals?

**Comment by TC1977** [comment]
Add a link to the comment please?

**Comment by benjaminshell** [comment]
Trail of Bits provides additional information in their [release announcement](https://blog.trailofbits.com/2016/12/12/meet-algo-the-vpn-that-works/). They explain that they don’t trust OpenVPN because of previous attack vectors and security incidents. However, one of the best things about Algo is WireGuard, which is designed to be simpler and more secure than both IPSec and OpenVPN.

**Comment by TC1977** [comment]
I think the reddit comment over-generalizes, as IPsec certainly has many different implementations and several of the distinctions don't apply as it's implemented here with strongSwan. Specifically #5, #6, #12. #2 isn't important, because you can be hacked through even one open port, #7 and #8 aren't actually distinctions, and I would also argue that OpenVPN has very extensive documentation (#9).

The distinctions that matter to me, as a VPN user who isn't a security-focused pro at all, is that IPsec and VPN On-demand support are built into iOS, so other people (i.e. wife) literally have to do nothing in order to have it work on their phones. OpenVPN can be set to work on an arbitrary port, which is nice if you're dealing with some (hostile) wi-fi that's blocking ports UDP/500 and UDP/4500. It also has better support for routers. However, Wireguard has an app and can work on an arbitrary port.

**Comment by dantheman213** [comment]
> Specifically 5, 6, 12. 2 isn't important, because you can be hacked through even one open port

Yeah but it's easier to open one port on an enterprise network than 3.

> VPN user who isn't a security-focused pro at all, is that IPsec and VPN On-demand support are built into iOS, so other people (i.e. wife) literally have to do nothing in order to have it work on their phones

I believe OP of reddit comment that point as well.

I think overall you have made cogent points but it'd be nice to here your full thoughts and strategy in the README of the project so that new users of your code can understand your thought process during certain key decisions and strategies that were made in the project.

**Comment by dguido** [comment]
I think the readme is clear why we consider OpenVPN less safe than StrongSwan.
