### ISSUE TITLE
failed: [localhost] (item=systemd-networkd)

### ISSUE THREAD

**Issue by rrengamani** [trailofbits/algo#1507]
I tried installing algovpn in windows using ubuntu18 and the installation went well. while running ./algo i end up getting below error for local host deployment.

TASK [common : systemd services enabled and started] ************************************************************
failed: [localhost] (item=systemd-networkd) => {"changed": false, "item": "systemd-networkd", "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\n"}
failed: [localhost] (item=systemd-resolved) => {"changed": false, "item": "systemd-resolved", "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\n"}

**Comment by jackivanov** [comment]
WSL will not work as the server, you have to use a dedicated server

**Comment by fnobilia** [comment]
Hi @jackivanov I'm new to the project and a bit confused.

The README mentions that algo can be installed in WSL ([reference](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md)), but this issue says it WSL does not support algo. Which one is the correct answer?

I am asking because I am having the exact same issue that @rrengamani reported last year. I'm running master branch on Windows 10Pro 1909.

If WSL is not supported, can I install algo in Ubuntu running inside VirtualBox hosted by my Window machine?

Thank you for your help! ;)
