### ISSUE TITLE
Can we automatically setup a unique DNS name for each server?

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#155]
I mostly dismissed this idea because I wanted to avoid asking for more API keys from the user.

What are the pros and cons of this potential feature? Does it introduce any new security or privacy risks? If the main benefit is being able to use Let's Encrypt certificates, is that something we even want to do?

Noting all this for further discussion later.

**Comment by dakami** [comment]
Sort of.  You can script EC2 Route 53 to register a domain and then add names to it.  Most of the cloud providers do have some degree of automatability, see:

http://libcloud.readthedocs.io/en/latest/dns/supported_providers.html

There's a universe of annoyance here, and you can't assign domains from autogenerated EC2 because someone else might actually end up with that exact domain someday.

I've been doing some goofy stuff on this issue for JFE; I'd just wait a month.

**Comment by gunph1ld** [comment]
EC2 has a public dns name for each instance like `ec2-52-53-197-23.us-west-1.compute.amazonaws.com`
we can use it

**Comment by defunctio** [comment]
I think this would introduce a lot of headaches and require functionality that would potentially be fragile. Also since we have moved certificate and key generation to the client side, this really seems unnecessary.

**Comment by samkelleher** [comment]
One thing I was wondering is if dedicated hostnames with reverse lookup working would reduce the number of times browsing via the VPN would be flagged as 'suspicious activity' by Google. For example, using a DigitalOcean, or even a Google Cloud, hosted instance of Algo, I get the robot prompt routinely when using Google services.

I wondered if they were greylisting domains like digitalocean/googlecloud which my IP would resolve to.

So I guess, would using dedicated DNS names help with that problem.
