### ISSUE TITLE
[Docker] "ERROR! the playbook:  could not be found"

### ISSUE THREAD

**Issue by samkelleher** [trailofbits/algo#1587]
**Describe the bug**

Docker image just fails on startup using example startup command from https://github.com/trailofbits/algo/blob/master/docs/deploy-from-docker.md.

The mounted directory contains the `config.cfg` copied from the repo root.

Image ID `sha256:fd4af1877b8d365341f799b55ab701eaddc77d69fe68fefb2d9006d1558e0126`
Docker for macOS version `19.03.2`

**To Reproduce**

1. `docker pull trailofbits/algo:latest`
2. `docker run --cap-drop=all -it 
  -v /Users/sam/VPNs:/data 
  trailofbits/algo:latest`

**Expected behavior**

**Additional context**

**Full log**

```
ERROR! the playbook:  could not be found
```

**Comment by ChieveiT** [comment]
the same here

**Comment by aidant** [comment]
The bug was introduced in #1582, something to do with the quotes that were added here https://github.com/trailofbits/algo/commit/0c3aada66fd641a849f0e854a281bd08858435af#diff-d4d5a054e84a627a039e26c697061d95R40.

A workaround is to define something in the ALGO_ARGS environment variable, for example:
```
docker run --cap-drop=all -it -e ALGO_ARGS="-e " -v <path>:/data trailofbits/algo:latest
```

**Comment by nihil-admirari** [comment]
https://github.com/trailofbits/algo/pull/1589 should fix the issue.
