### ISSUE TITLE
client with Internet kill switch like Bitmask

### ISSUE THREAD

**Issue by NIXOYE** [trailofbits/algo#165]
could algo use or fork Bitmask so we can have a client that stops all traffic once the vpn disconnects? This is especially required when using shoddy public wifi's.

https://bitmask.net/ does this prety well but its not as straight forward to become a Bitmask provider than it is to make a algo vpn

**Comment by gunph1ld** [comment]
no reason to fork 3rd pathy VPN client, because all modern OS have an IKEv2 client.
`OnDemandRules` already Implemented for Apple devices: https://github.com/trailofbits/algo/blob/master/algo#L39
for Windows you can execute bash script and route all traffic to the blackhole, the same situation for Linux (the updown module)

**Comment by NIXOYE** [comment]
@gunph1ld none of that compares to having a gui client that automatically stops traffic when you wifi disconnects, diplays that your not connected to the vpn and then automatically reconnects to vpn. especially if algo is trying to be straight forward for deployment and usage.
