### ISSUE TITLE
How do you manually packages?

### ISSUE THREAD

**Issue by Tokogon** [trailofbits/algo#1664]
Hi!

Newb user here that noticed his wireguard and dnscrypt proxy are several versions behind. I tried running "apt-get update & upgrade" but nothing upgrades.

I vaguely remember seeing an option in the config.cfg for the algo server to update automatically should I just leave it alone? The main reason i even care is that dnscrypt-proxy implimented CNAME blocking in its newest version and I'd love to be able to block these sneaky trackers.

**Comment by davidemyers** [comment]
Your AlgoVPN should automatically upgrade to latest version of WireGuard available from the [WireGuard PPA](https://launchpad.net/~wireguard/+archive/ubuntu/wireguard) and dnscrypt-proxy from the [dnscrypt-proxy PPA](https://launchpad.net/~shevchuk/+archive/ubuntu/dnscrypt-proxy). At the moment the most recent versions available are:
```
root@vpn4:~# dkms status
wireguard, 0.0.20191219, 5.3.0-24-generic, x86_64: installed
root@vpn4:~# dnscrypt-proxy --version
2.0.33
```
What versions are installed on your AlgoVPN?

There's an option in `config.cfg` to tell the AlgoVPN to reboot if an update requires it, otherwise it won't reboot on its own. Most updates don't require a reboot to take effect, though kernel updates do.

**Comment by Tokogon** [comment]
I have the same versions you just posted but just noticed its may actually only be dnscrypt-proxy that's behind. Oh well I guess I just need to wait on that PPA to update their repo. Sorry for wasting your time just thought my install was borked!
