### ISSUE TITLE
Intermittent failures on AWS EC2 in China

### ISSUE THREAD

**Issue by eh8** [trailofbits/algo#1667]
**Describe the bug**

Wireguard always successfully connects to the EC2 instance, but is unable to fetch webpages at random times for a few minutes before full functionality and speed is restored.

**To Reproduce**

1. Enter mainland China.
2. Connect to Wireguard/Algo.
3. Observe failures after 24 hours.

**Expected behavior**

Uninterrupted support. Or, at the very least, a definite end of life to the servers responsiveness when the govt detected the server?

**Comment by nikolaydubina** [comment]
I consistently experience similar connectivity issues from China. I am seeing this AWS EC2 and Lightsail and all regions (tried Singapore, Korea, Japan, Australia), same instance from outside China works fine. Typically, connection can go better after some delay (can be around 1 day). This issue has been around since early 2019, although a couple month ago got better (periods until degradation last longer).
