### ISSUE TITLE
Configure a local DNS server *without* ad blocking, more secure

### ISSUE THREAD

**Issue by natesilva** [trailofbits/algo#167]
Can algo be configured to use a local DNS server and *not* block ads? I want an unfiltered Internet experience, but I don’t want to trust an external DNS server.

Based on my limited understanding of DNS, pointing users to 8.8.8.8 and 8.8.4.4 allows interception or modification of DNS requests by the ISP (or an entity which has access to the ISP’s network).

Running a local server should be more secure. It would run all queries through the root server network -- and reject responses from recursive, rather than authoritative, servers. This ensures that the requests aren’t modified. Or at least, the ISP/entity will have to work harder to do so, since they would have to tamper with responses from many authoritative DNS servers, as opposed to emulating a single recursive server.

**Comment by dguido** [comment]
Just FYI, we considered this issue and ultimately decided against it. The main benefit of avoiding Google DNS is that you don't show up in their [temporary log](https://developers.google.com/speed/public-dns/privacy#what_we_log) of requests. Note that all requests to Google DNS are routed through the VPN tunnel when using Algo.

However, by forcing your DNS client to authoritative servers directly, you're exposing yourself to slow name servers, extraneous or malformed responses, malware and phishing domains, and other issues that Google DNS will [filter](https://developers.google.com/speed/public-dns/docs/security#mitigations) or [cache](https://developers.google.com/speed/public-dns/docs/performance#mitigations).

Since I can't think of a clear security risk right now (beyond the noted privacy risk above) that setting up a local resolver would solve, I'm content to leave it as-is for now.

**Comment by Thermi** [comment]
Bah. Authorative DNS servers very oftne (recommended and best practice setup) do not permit recursive queries, so you should run your own recursor with enabled DNSSSEC validation on your VPN server, if you care about speed and the threat model you described. The threat from malicious ISPs or generally hosts on the network path between you and your recursor is present as soon as the DNS queries or responses are transmitted over an untrusted network. It doesn't disappear when you point your client at another remote DNS server.
