### ISSUE TITLE
Unable to install on Ubuntu 18.04.3 on Digital Ocean

### ISSUE THREAD

**Issue by Crowned-Eagle** [trailofbits/algo#1823]
**Description**
I am using this guide to setup Algo VPN on Ubuntu 18.04 on Digital Ocean: https://zeltser.com/deploy-algo-vpn-digital-ocean/
After running ./algo and entering public IP the installation continues further but the installation is terminated with message:
```
Applying /etc/sysctl.conf ...
Job for wg-quick@wg0.service failed. See 'systemctl status wg-quick@wg0.service' and 'journalctl -xn' for details.
```

**To Reproduce**

Repeat commands in this guide: https://zeltser.com/deploy-algo-vpn-digital-ocean/

**Expected behavior**

Successful installtion of algo vpn

**Additional context**

This issue started today after I updated and restarted my VC running Ubuntu 18.04 on Digital Ocean today. After that I was unable connect my Algo VPN server. Also I was unable to start the wg-quick@wg0.service. Hence I deleted droplet and tried fresh deployment but this time installation is not going through successfully may be due to same error/cause.

**Comment by davidemyers** [comment]
There's an issue between a kernel update released yesterday by Ubuntu and the WireGuard module for 18.04. WireGuard should be fixed by now but maybe some repository mirrors have not updated yet.

The easiest fix is to use Ubuntu 20.04 since it doesn't rely on an external source for WireGuard.

To untangle the problem on your 18.04 server try this (assuming the repository mirrors are current):
```
sudo apt update
sudo apt upgrade -y
sudo reboot
sudo apt remove wireguard
sudo apt install wireguard
```

**Comment by CA2MI** [comment]
Unfortunately my repository isn't current... ugh. So if I move things to 20.04 it should resolve things like this in the future?

**Comment by davidemyers** [comment]
Yes. This problem, which has now happened twice, should not occur on 20.04 because that kernel ships with WireGuard, therefore use of a third-party repository is not required. Algo defaults to 20.04 on all supported cloud providers where it's available. It's possible to use the 20.04 kernel on 18.04 on cloud providers which don't use custom kernels but I'm not sure it's worth the trouble.

I think the trick to resolving this issue on a messed-up 18.04 system is to install *and boot* to the latest kernel, then reinstall WireGuard. Instead of the remove/install commands I posted above this might also work:
```
sudo dpkg-reconfigure wireguard-dkms
```

**Comment by CA2MI** [comment]
That one did it on the one I tried the first stuff you posted. I have a few I need to up date and will let you know. I have a few on 18.04 and a few on 20.04. I didn't see the issue show up on the 20.04 and was wondering why :) Thanks for the quick responses.

**Comment by CA2MI** [comment]
It looks like the single command

"sudo dpkg-reconfigure wireguard-dkms"

didn't work. But doing the first and second parts one after the other fixed my issue.

**Comment by Crowned-Eagle** [comment]
@davidemyers Thanks for the quick reply..
