### ISSUE TITLE
Review and document our iptables configuration

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#190]
Our iptables rules for Algo VPN are fairly involved. I think we should document what each one is for and review the overall configuration. StrongSwan has an [FAQ](https://wiki.strongswan.org/projects/strongswan/wiki/FAQ#IPsec-and-iptablesnftables) where they try to shed some light on how IPSEC is processed by iptables that might help.

Here are the relevant files:
https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v4.j2
https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v6.j2

**Comment by kennwhite** [comment]
Just my 2¢, but I would move this to 1.1, and ideally reach out (even informally) to someone on the strongswan or even the libreswan teams for a quick review. This is heady stuff, and easy to bork up with a trivial mistake.

**Comment by mrled** [comment]
Hi, I was looking at trying to document this, but I came across a question looking at the IPv4 rules file, specifically on [line 34](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v4.j2#L34). (I haven't looked at the IPv6 file in detail yet, but it doesn't appear to have a similar rule.) That line says:

    -A INPUT -d {{ local_service_ip }} -p tcp -m multiport --dport 8080,8118 -j ACCEPT

It appears to allow traffic to the "local service IP", which is the local DNS resolver address, which is 172.16.0.1 by default.

Is this intentional? My Algo server doesn't have anything listening on either of those ports.

**Comment by mrled** [comment]
Hmm. It looks like Algo used to install privoxy. I think I'm going to assume that these ports were used by that application, but that they're no longer necessary since that functionality was removed. https://github.com/trailofbits/algo/pull/457
