### ISSUE TITLE
Question: How to upgrade?

### ISSUE THREAD

**Issue by farahats9** [trailofbits/algo#1922]
Hi, I use the version from the master branch and I see it gets updated frequently. Is there security benefit to doing git pull when there are new commits or should I stick to the release which was in 2019?
also after pulling the latest version is there anything required to apply the updates after pulling?

**Comment by davidemyers** [comment]
Here's what I suggest (this is just one person's opinion):

Start with a fresh `git clone` and deploy your server(s). Keep the copy around for the life of your server(s) so that you can `./algo update-users` if needed. Don't use `git pull` or you could break things.

If there have been more than a few commits by the time you're ready to deploy more servers, use a fresh `git clone` again so you get all the changes.

Renaming an `algo` directory can break it due to the way the Python virtual environment is created so I clone into uniquely named directories:
```
git clone https://github.com/trailofbits/algo.git algo-$(date +%F)
```
Note that there is no mechanism to update a deployed AlgoVPN server other than adding users. The server will take care of updating software packages for security and bug fixes as updated packages are released by Ubuntu.
