### ISSUE TITLE
Hotspot avoidance

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#208]
We should help users avoid hotspots where ever possible.

It is possible to make Apple profiles for wifi networks that know how to log in to specific captive portals. There is one older, outdated app named "AutoWifi" that attempts to log in to arbitrary captive portals automatically.

It would be useful if we could make a profile, or make an app, that does this again.

**Comment by kennwhite** [comment]
Fwiw, having used 3 different captive portals today, and Algo had no problem configured with the always on cell+wifi profile. Got an embedded mini-page in iOS settings when I clicked on the hotspot name. One was paid (yay for pre-paid Visa gift cards and 90210 references), the other two were just agree to terms.

**Comment by dguido** [comment]
The Apple on-demand VPN is smart enough to let the user login to captive portals before connecting, but I want to avoid Safari loading any untrusted, local Javascript. It's a security issue.

**Comment by pwnsdx** [comment]
Generally those who runs a Captive Portal block IKEv2 (or more generally IPSec or worst, UDP).

You can block Captive Portals by using Always-On VPN instead of On Demand VPN.

I attached the profile I made if you want (macOS does not support Always-On VPN).

[Server.mobileconfig.zip](https://github.com/trailofbits/algo/files/846149/Server.mobileconfig.zip)

**Comment by dguido** [comment]
This is outside the scope of what we can achieve with this version of Algo
