### ISSUE TITLE
Suggestions for SSH

### ISSUE THREAD

**Issue by pwnsdx** [trailofbits/algo#272]
### OS / Environment

Ubuntu Server

### Summary of the problem

- It would be nice to not setup an additional SSH key when using the choice 5 (Install to existing Ubuntu server) since Algo already use SSH to login to the server.
- RSA 2048 bits key is used for SSH ( https://github.com/trailofbits/algo/blob/f7da2e3888a882d2fd2e51883d48c05627f00a21/playbooks/local.yml#L4 ). I think it would be better to use RSA 4096 bits or much better, use modern crypto like Ed25519 / Curve25519.

- I noticed that the misleading "RSAAuthentication" option is present and is set to "No".

I suggest to remove it in the sshd_config file: https://github.com/trailofbits/algo/blob/dbeb7a13e88463b5b939739c36e59746f9af5758/roles/security/templates/sshd_config.j2#L29

RSAAuthentication was used as a way to allow pubkey auth in SSH v1. This option does not exist anymore and has been replaced by PubkeyAuthentication since ECDSA support has been added (https://github.com/trailofbits/algo/blob/dbeb7a13e88463b5b939739c36e59746f9af5758/roles/security/templates/sshd_config.j2#L23)

- The chosen name of the public / private key is not respected.

https://github.com/trailofbits/algo/blob/master/config.cfg#L59
https://github.com/trailofbits/algo/blob/f7da2e3888a882d2fd2e51883d48c05627f00a21/playbooks/local.yml#L9
https://github.com/trailofbits/algo/blob/f7da2e3888a882d2fd2e51883d48c05627f00a21/playbooks/local.yml#L14

-> algo.pem is used instead of the user's choice

### The way of deployment (cloud or local)

local

**Comment by pwnsdx** [comment]
Other minor issue: The chosen name of the public / private key is not respected.

https://github.com/trailofbits/algo/blob/master/config.cfg#L57
https://github.com/trailofbits/algo/blob/f7da2e3888a882d2fd2e51883d48c05627f00a21/playbooks/local.yml#L9
https://github.com/trailofbits/algo/blob/f7da2e3888a882d2fd2e51883d48c05627f00a21/playbooks/local.yml#L14

-> algo.pem is used instead of the user's choice

**Comment by pwnsdx** [comment]
> I think it would be better to use RSA 4096 bits or much better, use modern crypto like Ed25519 / Curve25519.

Something like this would be nice:

1. Delete all existing keys if the Algo SSH host key does not exist
2. Then generate a new host key using ed25519

```
if [ ! -e "/etc/ssh/ssh_host_ed25519_key_algo" ]; then /usr/bin/rm /etc/ssh/ssh_host_*key*; /usr/bin/ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key_algo -N \"\" < /dev/null; fi
```

**Comment by jauderho** [comment]
I agree that it would be much preferable to use ed25519 keys. Ideally, that would be the only type allowed but might be too draconian. 

Otherwise, you could have "high security" vs. "normal" configs.

**High security**
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

**Normal**
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group14-sha1
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ssh-rsa-cert-v01@openssh.com,ssh-rsa
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
