### ISSUE TITLE
Test our support for Android VPN Profiles

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#280]
We can now generate all-in-one profiles for users of the Android StrongSwan app.

https://github.com/trailofbits/algo/commit/aca036142fb14c037ea457a72881580b757745a9

We should test to make sure this feature works as expected and update any relevant documentation for it.

**Comment by defunctio** [comment]
I tested this on an emulator a week or so ago without success, needs to be reviewed further.

**Comment by gunph1ld** [comment]
Very painful to open this file on Android neither native file browser nor downloads don't want to open it in the strongswan app. I was able open the file only from the Google Chrome downloads

**Comment by jonahbull** [comment]
Very painful is right. On Android 7.1.2 (Nexus 5X), the only way I could get the profile to open was serving the directory containing the profile on my local network via a SimpleHTTPServer (`python -m SimpleHTTPServer`) and clicking on the link in Chrome. Downloading the file and then trying to open via native file browser or downloads (Chrome and system) did not work at all. 

SimpleHTTPServer uses `application/octet-stream` as its default mime type, so as a second test I set up SimpleHTTPServer to serve `.sswan` files with the mime type `application/vnd.strongswan.profile` as indicated by the [strongSwan wiki](https://wiki.strongswan.org/projects/strongswan/wiki/AndroidVPNClientProfiles). With the correct mime type set, downloading the file and opening it via downloads _did_ work. That's not exactly a great user experience, though the fault seems to lie with the strongSwan Android app, rather than anything on the Algo side.

**Comment by tobiasbrunner** [comment]
The workaround from #554 is not necessary anymore. Since the recently released version 1.9 of the strongSwan app it is possible to browse for profile files to import from within the app (neither the file extension nor MIME type does matter in this case).
