### ISSUE TITLE
QUESTION:  How can you change initial settings after the server's up and running?

### ISSUE THREAD

**Issue by natelandau** [trailofbits/algo#283]
I neglected to enter my home wifi network when first running the script.  I've been looking through the docs but I can't seem to find reference to where I can add/remove networks from this list after the server is up and running.

I also set it to connect over cellular networks. Everything's working perfectly, I just don't know the steps to change these settings on the fly?

Do you need to delete the certificate and the VPN server and start over?

**Comment by deansaxe** [comment]
From what I am able to tell, you can't change it on the fly.  You'll need to run through the Ansible config again, change your settings, and reinstall the VPN configs.

**Comment by dguido** [comment]
In general:
Once it sets up the server, it's yours to manage. We provide one helper script for user management since that's a common use case. One of the major benefits of using Algo is that, after the first deploy, successive deploys are trivially easy. If you want to change any settings, I generally recommend destroying the VM and redeploying a new one.

For your case: the settings you are talking about are managed on the client, not the server. You can modify the Apple Profile by opening it in a text editor or Apple Configurator and resaving it.
