### ISSUE TITLE
Move documentation to GitHub Wiki

### ISSUE THREAD

**Issue by mmattioli** [trailofbits/algo#371]
The documentation is fairly thorough and complete but it seems as though it's starting to become somewhat unorganized; the Markdown files are being written and tossed into `docs/` with links in `README.md` but perhaps breaking things down into sensible chunks of information and organizing them in the repo's Wiki would make things more easily navigable.

**Comment by dguido** [comment]
Thanks! Maybe soon... I like having the docs in the repo because we have had many others submit PRs against them to fix issues. If we moved to the Wiki, we would have to lock it down to only team members and collaborators. Eventually, I think pointing Github Pages at the /docs/ directory would be a good idea too. Finally, normal users should be completely satisfied by the information on the main README. Docs elsewhere are also for advanced or non-standard use cases, which limits the hunting that anyone needs to do.

So for now I prefer sticking with in-repo documentation. Are there other advantages I'm forgetting about?

**Comment by mmattioli** [comment]
I'll submit a PR to reorganize the `docs/` directory for use with GitHub pages if you think that's a fair approach.

**Comment by dguido** [comment]
Sure go for it.
