### ISSUE TITLE
Upgrade base image to Ubuntu 17.04

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#449]
Mainly for strongSwan 5.5.1. We care about 5.5.1 because it avoids the dead peer detection bug for macOS and iOS.

17.04 is available on EC2 and Digital Ocean already. It is not yet available on Azure or Cloud Engine yet.

**Comment by dguido** [comment]
@gunph1ld Can you add a config flag to the config.cfg that lets you select 17.04? I think 17.04 will "just work" as long as the cloud hosting provider supports it (AWS and DigitalOcean do). Leave the default at 16.04 obviously.

**Comment by davidemyers** [comment]
In 17.04 with the security role deployed I'm seeing some new log spam every time some bot tries to log in:

`Apr 23 12:44:38 vpn1 sshd[2607]: rexec line 28: Deprecated option RhostsRSAAuthentication`

Looks like SSH has changed from 16.04. This option can probably just be removed altogether since the `sshd_config` man page from 16.04 says,

     RhostsRSAAuthentication
             Specifies whether rhosts or /etc/hosts.equiv authentication
             together with successful RSA host authentication is allowed.  The
             default is “no”.  This option applies to protocol version 1 only.

And `sshd_config` already specifies only to use version 2.

**Comment by bjornlll** [comment]
Any tentative date where we'll be able to run on Ubuntu 17.04? Alternatively, is there any way I can try out running on 17.04 right now? The VPN keeps dropping out on my iPhone, that's why I'm asking.

**Comment by dguido** [comment]
16.04 works fine with our workaround.

As described in #466, distro version is configurable in config.cfg now.

**Comment by gunph1ld** [comment]
All the cloud providers we use provide 17.04 now. We can switch to it permanently

**Comment by bjornlll** [comment]
Curious: Is there any upside to switching now that 16.04 has the stongSwan patch we were waiting for?
