### ISSUE TITLE
How to stop/pause Algo

### ISSUE THREAD

**Issue by aignermichael** [trailofbits/algo#485]
### OS / Environment
MacOS X

### Ansible version
ansible 2.2.0.0

### Summary of the problem

I run Algo on AWS and i'm wondering what is the best strategy to use it only partially. Is the best way to everytime shutdown the EC2 instance and create a completely new configuration or should I just stop the EC2 instance and boot it up again when i need a VPN? Do you guys also offer command line tools for stopping or terminating the created EC2 instances?

Last thing, are there any solution out to run Algo on Mobile - and with run i mean starting up a new server?

**Comment by dguido** [comment]
> Last thing, are there any solution out to run Algo on Mobile - and with run i mean starting up a new server?

No, not right now.

> Is the best way to everytime shutdown the EC2 instance and create a completely new configuration or should I just stop the EC2 instance and boot it up again when i need a VPN? Do you guys also offer command line tools for stopping or terminating the created EC2 instances?

I make new servers for every trip I go on.

**Comment by jaap** [comment]
@aignermichael 
Instead of creating a new server I make use of the AWS CLI console to start/stop the EC2 instance.
A very basic shell script which I use to starts/stops the instance. Just add your region and instance id and trigger the script with start/stop argument.

'./ec2 start'
'./ec2 stop'

Not the most elegant solution, but quick.

https://gist.github.com/jaap/b1659a8b84afcb20f1a660e153bc3a29

**Comment by rjh336** [comment]
@jaap - will your solution still work upon starting up the instance again since AWS will reassign your ec2 instance a new IP?

@dguido - is there a place(s) in the algo config where we can overwrite the IP of our algo server, or must we rebuild the server from scratch?

**Comment by TC1977** [comment]
AWS charges for static IPs when not in use. So if you've stopped an Algo server with a static IP, you'll be charged per hour. If you've removed the static IP, then when you restart it, it will be assigned a different IP. Then your existing mobile config won't work. You could try to modify it, but the certificate will also be different (since it's based on the server IP). I guess there's a way to modify the certificate as well? ...but even then, you'd have to distribute the new mobile config files anyway. So you wouldn't have saved any time.

Really the easiest, fastest, and most secure way to go is just blow up the server when you're done, and create a new server (using the latest version) when you need a new one.

**Comment by jaap** [comment]
Fair point TC1977, which I encountered as well and forgot to mention.
If you've got other EC2's running you could attach it to that, but in the end I agree with TC1977. Spinning a new one up might be the best solutions when using Algo sporadically.
On the other hand. Running an ec2 micro 24/7 would cost < $5 a month.
If you would use Algo a few times a month, especially on mobile, where installing takes a bit more effort, I would say it's not worth the hassle and just keep it running.
