### ISSUE TITLE
Tighten the iptables firewall policy

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#61]
- [x] We should DROP or REJECT CIFS/SMB traffic, otherwise NTLM hashes could leak. Website with [exploit](http://witch.valdikss.org.ru/) and [writeup](https://medium.com/@ValdikSS/deanonymizing-windows-users-and-capturing-microsoft-and-vpn-accounts-f7e53fe73834#.ea4q8fkap).
- [x] Filter in *filter FORWARD for traffic to the roadwarrior clients.
- [x] We probably want to use a ULA when using an IPv6 pool for RWs, so it is very unlikely the VIP of the RW collides with the local subnet.
- [x] Drop neighbor traffic in *filter FORWARD
- [x] Simply enabling net.ipv4.ip_forward=1 may not be sufficient. We might also have to enable packet filtering for the interfaces we specifically want to use.
- [ ] Review https://medium.com/@ValdikSS/detecting-vpn-and-its-configuration-and-proxy-users-on-the-server-side-1bcc59742413

**Comment by Thermi** [comment]
Register a ULA here to prevent a collision: https://www.sixxs.net/tools/grh/ula/
then use it.
two iptables rule sets are attached. The one for ip6tables drops invalid neighbor packets that netfilter can forward (devs know about this and might patch netfilter to automatically drop them when they're forwarded. https://www.insinuator.net/2016/05/cve-2016-1409-ipv6-ndp-dos-vulnerability-in-cisco-software/. The problem is not Linux.The problem is other implementations, which might be buggy)
It's not `packet filtering`. It's `packet forwarding`.
Set `net.ipv4.conf.all.forwarding` to "1".
[iptables_ip6tables.tar.gz](https://github.com/trailofbits/algo/files/426024/iptables_ip6tables.tar.gz)

**Comment by dguido** [comment]
:+1:

**Comment by gunph1ld** [comment]
What is the difference between `net.ipv4.conf.all.forwarding` and `net.ipv4.ip_forward` ?
`net.ipv4.ip_forward` is more global and It has exactly the same effect as `net.ipv4.conf.all.forwarding`.
I see no reason to use `net.ipv4.conf.all.forwarding`

**Comment by gunph1ld** [comment]
I registered ULA, but I think ULA is just LOL and nothing else. 
No more 0.01% of whole the world will use it

**Comment by Thermi** [comment]
I previously did not know that "net.ipv4.ip_forward" does turn the knobs for all interfaces, too, but I previously had instances where even though forwarding was globally allowed, it was not allowed for the interfaces involved. I think it would be safe to set "net.ipv4.conf.all.forwarding", too.

As previously pointed out, it is very very unlikely that a registered ULA will be used by another party, therefore I think it contributes to the goal that a client connecting to VPN does not introduce any change  to the local network (As I previously wrote, it can be that the DHCP range of the local network contains the roadwarrior's IP and then it can be that it responds to pings and takes up a DHCP lease or causes double usage of that IP in the LAN.This is primarily caused by the weak IP host model of Linux and the fact that, by default, it responds to any valid ARP requests for a local IP that it receives on any interface. It is likely that this is the default behaviour of any other client. For Linux, it can be disabled by setting the "arp_ignore" key in sysctl, as described on https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt )

**Comment by gunph1ld** [comment]
The probability of have the same IPv6 ranges and have a collision is very small

**Comment by dguido** [comment]
We should move the IPtables rules out of the `security` role and into the `vpn` role, since they are not really an "enhancement" but are instead kind of essential for operating the VPN securely.

**Comment by dguido** [comment]
Hey @gunph1ld: Did we ever move the IPTables rules from the security role and into the vpn role? They are essential for the VPN, so shouldn't make them optional.
