### ISSUE TITLE
The parameter is incorrect

### ISSUE THREAD

**Issue by khiren** [trailofbits/algo#630]
### OS / Environment

Windows 10

### Ansible version

2.2.0

### Summary of the problem

I set up and followed the steps for algo on windows 10. I set it up on my laptop which is windows 10. And when i try to connect the vpn it comes saying "cant connect to algo vpn, the parameter is incorrect.

### Steps to reproduce the behavior
Well i set up digital ocean 1st and the error came there. so i set up AWS and the same issue.

**Comment by ThoAppelsin** [comment]
I had the same issue, and resolved it by following the very simple steps on Stack Exchange's Super User: https://superuser.com/a/1181732/353054

At step 3, instead of removing the `WAN Miniport (PPTP)`, remove `WAN Miniport (IKEv2)`. At least this is how I got mine working on my laptop, after having tried both Azure and Digital Ocean with no luck.
