### ISSUE TITLE
Windows Client Setup

### ISSUE THREAD

**Issue by kevingrijalva** [trailofbits/algo#637]
### OS / Environment

Windows 10/Amazon EC2

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
Name: setuptools
Version: 20.7.0
ansible-2.2.0.0
msrestazure-0.4.11
boto3-1.4.4
azure==2.0.0rc5
boto 2.5.0
msrest==0.4.1
 six-1.10.0-
pyOpenSSL-17.2.0
Jinja2-2.8

### Summary of the problem
My algo server is up and running fine. I am attempting to configure it to my Windows 10 client.
I've copied the CA certificate (cacert.pem), user certificate ($user.p12), and the user PowerShell script (windows_$user.ps1) to my client computer.
I imported the CA certificate to my trusted root certificate store

When I attempt to run the powershell script as an administrator with unrestricted execution policy I get 
the following

PS C:\WINDOWS\system32\vpn> Set-ExecutionPolicy Unrestricted -Scope CurrentUser

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y

PS C:\WINDOWS\system32\vpn> .\windows_useradmin.ps1 Add
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
Add-VpnConnection :  This VPN connection has already been created. Specify a different VPN profile name. : Cannot
create a file when that file already exists.
At C:\WINDOWS\system32\vpn\windows_useradmin.ps1:5 char:3
+   Add-VpnConnection -name "Algo VPN 34.231.202.139 IKEv2" -ServerAddr ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Algo VPN 34.231.202.139 IKEv2:root/Microsoft/...S_VpnConnection) [Add-V
   pnConnection], CimException
    + FullyQualifiedErrorId : WIN32 183,Add-VpnConnection

Set-VpnConnectionIPsecConfiguration : A parameter cannot be found that matches parameter name 'IntegrityCheck$'.
At C:\WINDOWS\system32\vpn\windows_useradmin.ps1:6 char:192
+ ... ansformConstants GCMAES128 -EncryptionMethod AES128 -IntegrityCheck$}
+                                                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-VpnConnectionIPsecConfiguration], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-VpnConnectionIPsecConfiguration

### The way of deployment (cloud or local)
cloud

### Expected behavior
Additionally, I've attempted to add the user certificate to trusted root certificate authorities manually, but receive the following error: 
The file type is not recognizable. Select another file.

and when I attempt to double click the .p12 file I get:
Invalid Public Key Security Object File
This file is invalid for use as the following: Personal Information Exchange

Maybe the powershell script requires more parameters and I just don't know how to run it properly, but I still am not able to configure my client manually.

**Comment by catcarbon** [comment]
For your Windows to recognize the CA, you have to install the CA rather than your user certificate. 

By default the CA is not retained once algo is deployed. If you would prefer install the CA, enter y when the deployment script asks whether you want to retain the certificate. 

Double clicking on the *.crt file generated should give you some nice installation prompt. Then remove the created VPN connection from Connection Manager phonebook and re-run the [Windows client setup script](https://github.com/trailofbits/algo#windows-10). 

As you have changed your Execution Policy, please be sure to revert it. To my knowledge, `Set-ExecutionPolicy Default -Scope CurrentUser`(with Administrator) would do the work. 

Source: 
- [About Execution Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies)
- [Set-ExecutionPolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy)
