### ISSUE TITLE
MTU problem

### ISSUE THREAD

**Issue by UncleBod** [trailofbits/algo#790]
### OS / Environment

Microsoft Azure

### Ansible version

Not installed

### Summary of the problem
MTU roble. Some sites wont load

### The way of deployment (cloud or local)
cloud

### Expected behavior
All sites should load

### Actual behavior
Not ll sites loads

### Full log

Where is the log?

**Comment by st1905** [comment]
Its due to MTU, use iptables to adjust it

`iptables -t mangle -A FORWARD -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360`

And add following to the sysctl.conf and apply it with sysctl -p command

`net.ipv4.ip_no_pmtu_disc=1`

Fixes all issues with https sites. Everything works.

**Comment by st1905** [comment]
And if you are wondering why reducing mss fixes this issue, take a look at here, [https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/](url) excellent piece of information.

**Comment by UncleBod** [comment]
OK,
now a thing that not have been clear in threads I read earlier:
Is this to be done on the server?

**Comment by st1905** [comment]
That`s right, only server side.

**Comment by UncleBod** [comment]
Thanks.
Works as it should now.
For clarification:
it should be the file
`/etc/sysctl.conf`

And unless you log in as root (you shouldn't) both commands should be prepended with
`sudo`


I will read that text a bit later. (longing back to teh time 1200 bps was fast. Networking was so much easier then...)
