### ISSUE TITLE
"Password is not correct" when installing mobileconfig files

### ISSUE THREAD

**Issue by LeilaAhmad** [trailofbits/algo#857]
I'm using the same password that is generated after installing the vpn.

**Comment by watkinsmd** [comment]
I am having the same issue; was this resolved or is there a documented fix for this elsewhere? mobileconfig on my Mac running Mojave works fine (double click the file, enter the password generated during Algo deploy, connect). On Phone X running iOS 12.0.1 the mobileconfig file was sent via AirDrop. When prompted for the password in iOS, I am getting the error that the password is invalid despite using the same password that works fine in Mojave on a Mac. I've destroyed a droplet and re-deployed and I am getting the same result on iOS. Note that I am using the same user name for each device. I deployed Algo years ago but abandoned its use due to disconnects (I posted my issue which resulted in issue #346 being opened). When I initially deployed Algo I was able to use the same user name on multiple devices and a password was not required. I am attempting to use it again now that I see that issue has been closed using DigitalOcean.
