### ISSUE TITLE
Add support for Cloudflare's 1.1.1.1 DNS

### ISSUE THREAD

**Issue by Cauchon** [trailofbits/algo#861]
Could we add built-in support for Cloudflare's new privacy focused DNS? 

https://blog.cloudflare.com/announcing-1111/
https://1.1.1.1/

**Comment by cdolle** [comment]
There were a bunch of posts about moving away from GoogleDNS with the release of Quad9's 9.9.9.9 resolver, too.  I think they ultimately decided against it because Google's logging policy on their public DNS service isn't actually too bad, it's really reliable, and Google is already doing a bunch of malware filtering. 

And while it's not part of the command line setup process, if you're wanting to use a different DNS service, it's simple enough to edit in config.cfg.

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/pull/862#issuecomment-377835814
