### ISSUE TITLE
iOS Always on vs On Demand?

### ISSUE THREAD

**Issue by HenkiedeHenkie** [trailofbits/algo#896]
Ok, I know this is not a Algo related issue but as there are several topics in the Issues section and iOS and Mac OS profiles are an integral part of Algo's configuration I think it's interesting to bring this up. At the moment, I'm having troubles figuring out the main differences between the On Demand vs the Always On iOS VPN settings. Even Apple's own documentation doesn't seem to provide much clarity, What are the main differences between the two? What are the major benefits/drawbacks comparing the two? This would help me a lot! Thanks in advance!

**Comment by jwebbstevens** [comment]
Basically if the VPN is accessible the connection will be created automatically on boot up using _Connect on Demand_ toggle in the settings section of the VPN info in iOS. You can set this default in Algo but always change the settings on the profile afterwards if you don't like it or need to toggle it on off.

For instance you boot up your iPhone or Mac and the VPN will turn on automatically, its helpful if you set MacOS to display connect time (a counter of how long the VPN has been connected to your local device). That way you know it's on.

_Connect on Demand_ essentially forbids you from 'turning' the VPN off unless you go deeper into the settings of the VPN. In effect you're telling the local machine always connect. This can be problematic if you are browsing a website that blocks your IP (some commercial sites use AKAMAI and other tools to flag what they perceive as errant IP addresses) because you'll have to dig into the VPN settings to turn off the connect on demand toggle of in order to get to those websites. (See issue #803)

Otherwise with this off you have to remember to turn on the VPN before you go online, depending on your security needs this may impact what your ISP sees, etc.

![connect on demand](https://user-images.githubusercontent.com/7277574/39321593-71128e1a-4955-11e8-9ee6-c8a7ea40158e.png)

**Comment by HenkiedeHenkie** [comment]
Clear. So what's the difference with the Always on Mode then? And how do I prevent any public IP leaks when the device phones home to Apple?

**Comment by jwebbstevens** [comment]
I don't know where your referring to Always on mode? Where are you seeing that?

IP leaks happen for a lot of reasons.

- You can use [DNS Leak test](https://www.dnsleaktest.com/results.html) to check for leaks. I kind of like [Whoer.net](https://whoer.net/) test and how they break out the information from an IP check visually too
- WebRTC can leak IP and usually the primary culprit as well so using a browser that you can turn that off WebRTC or toggle it as needed.  As of the latest versions of Chrome that's not the case but browsers like Firefox allow you to toggle that off. 
-Browser extensions can leak your local IP as well, so do your research on which ones work. Some people turn them all off and use none but I find HTTPSEverywhere to useful to ditch it.
- You can turn off the telemetry data too in Firefox which helps 
- The Algo team also made updates to use default name servers too  Issue #809

**Comment by dguido** [comment]
Please use the issue search before filing new issues!

https://github.com/trailofbits/algo/issues/278

**Comment by enxoco** [comment]
"Always On" is only available on iOS devices that are supervised.  With "Always On" mode, the VPN is always on and their is no option for the user to turn it off.  The iOS device must be "Supervised" to enable this.  Supervising an iOS device requires erasing it and using a program from apple called Apple Configurator.
